### ISSUE TITLE
ECMAScript 6 syntax in transformation

### ISSUE THREAD

**Issue by klasen** [PointBlueTechnology/EnhancedIDMCollector#9]
`base64DecodeToBytes` uses block scoped variables (`const` and `let`). Is that supported by the JavaScript engine used in IG?

**Comment by jcombs-pointblue** [comment]
It is. It took some trial and error to find a way that worked. What is in the readme now is tested and working.

From: Norbert Klasen ***@***.***>
Date: Friday, April 5, 2024 at 10:16 AM
To: PointBlueTechnology/EnhancedIDMCollector ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [PointBlueTechnology/EnhancedIDMCollector] ECMAScript 6 syntax in transformation (Issue #9)

base64DecodeToBytes uses block scoped variables (const and let). Is that supported by the JavaScript engine used in IG?

**Comment by klasen** [comment]
IG seems to be using Nashorn (https://github.com/openjdk/nashorn) instead of Rhino as the other NetIQ Identity products.
